"""adiciona card_reference em payments

Revision ID: 4dbdbb200c53
Revises: e4b8bebd1ee0
Create Date: 2026-09-12 11:16:17.383377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dbdbb200c53'
down_revision = 'e4b8bebd1ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_reference', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('card_reference')

    # ### end Alembic commands ###
