"""adiciona location_id em orders

Revision ID: 6ed07d8c529b
Revises: e709d65ee3ed
Create Date: 2026-09-11 18:02:25.898244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed07d8c529b'
down_revision = 'e709d65ee3ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_orders_location_id', 'stock_locations', ['location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_location_id', type_='foreignkey')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###
